package server

import (
	_ "Integrate.Interview.Backend.Golang/docs" // docs is generated by Swag CLI, you have to import it.
	"Integrate.Interview.Backend.Golang/server/controllers"
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"log"
	"net/http"
)

var (
	router      *mux.Router
	routerdocs  *mux.Router
	httpManager controllers.Manager = controllers.NewController(&controllers.ControllerManager{})
)

func init() {
	ApiSetup()
	DocsSetup()
}

type Routes struct {
	Name        string
	Method      string
	Path        string
	HandlerFunc func(w http.ResponseWriter, r *http.Request)
}

var routes = []Routes{
	Routes{
		Name:        "HealthCheck",
		Method:      "GET",
		Path:        "/health",
		HandlerFunc: httpManager.HealthCheck,
	},
	Routes{
		Name:        "Leads",
		Method:      "GET",
		Path:        "/leads",
		HandlerFunc: httpManager.AllLeads,
	},
}

func ApiSetup() {
	router = mux.NewRouter()
	for _, route := range routes {
		router.HandleFunc(route.Path, route.HandlerFunc).Methods(route.Method)
	}

	router.Use(loggingMiddleware)
}

// @host localhost:8084
// @BasePath /
func DocsSetup() {

	routerdocs = mux.NewRouter()
	routerdocs.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), //The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("#swagger-ui"),
	))
}

func loggingMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Content-Type", "application/json")

		log.Println(r.RequestURI)
		// Call the next handler, which can be another middleware in the chain, or the final handler.
		next.ServeHTTP(w, r)
	})
}
