basePath: /
definitions:
  controllers.Result:
    properties:
      errors:
        items: {}
        type: array
      result: {}
    type: object
host: localhost:8084
info:
  contact: {}
paths:
  /health:
    get:
      description: get server health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Result'
            type: array
        "500":
          description: ""
      summary: Health Check
      tags:
      - health
  /leads:
    get:
      description: Returns Array of Lead Results
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Result'
            type: array
        "500":
          description: ""
      summary: Get All Lead Data
      tags:
      - leads
swagger: "2.0"
